# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-30 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160730_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category__products', to='core.Category'),
        ),
        migrations.AlterField(
            model_name='productparam',
            name='attributeType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_param__attribute_type', to='core.AttributeType'),
        ),
        migrations.AlterField(
            model_name='productparam',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product__params', to='core.Product'),
        ),
    ]
